import type { Supplier } from "@/types/supplier";

const baseTimestamp = "2026-04-20T09:00:00.000Z";

export const mockSuppliers: Supplier[] = [
  {
    id: "sup-001",
    companyName: "Northshore Components",
    contactPerson: "Ava Martinez",
    email: "ava@northshorecomponents.com",
    phone: "+12065550101",
    country: "United States",
    productCount: 128,
    status: "ACTIVE",
    notes: "Primary electronics supplier for industrial displays.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-002",
    companyName: "Maple Leaf Packaging",
    contactPerson: "Liam Bennett",
    email: "liam@mapleleafpackaging.ca",
    phone: "+14165550102",
    country: "Canada",
    productCount: 74,
    status: "ACTIVE",
    notes: "Eco-friendly cartons and shipping inserts.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-003",
    companyName: "Monterrey Metals",
    contactPerson: "Sofia Hernandez",
    email: "sofia@monterreymetals.mx",
    phone: "+52815550103",
    country: "Mexico",
    productCount: 42,
    status: "PENDING",
    notes: "Aluminum housings awaiting compliance paperwork.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-004",
    companyName: "Rio Verde Textiles",
    contactPerson: "Lucas Almeida",
    email: "lucas@rioverdetextiles.com.br",
    phone: "+55115550104",
    country: "Brazil",
    productCount: 91,
    status: "ACTIVE",
    notes: "Specializes in recycled fabric blends.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-005",
    companyName: "Thames Trade Goods",
    contactPerson: "Charlotte Reed",
    email: "charlotte@thamestrade.co.uk",
    phone: "+44205550105",
    country: "United Kingdom",
    productCount: 56,
    status: "INACTIVE",
    notes: "Paused after price renegotiation cycle.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-006",
    companyName: "Bavaria Precision Parts",
    contactPerson: "Jonas Fischer",
    email: "jonas@bavariaprecision.de",
    phone: "+49895550106",
    country: "Germany",
    productCount: 147,
    status: "ACTIVE",
    notes: "High-volume CNC partner with weekly replenishment.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-007",
    companyName: "Lumiere Plastiques",
    contactPerson: "Camille Laurent",
    email: "camille@lumiereplastiques.fr",
    phone: "+3315550107",
    country: "France",
    productCount: 63,
    status: "PENDING",
    notes: "Prototype mold supplier for new kitchen line.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-008",
    companyName: "Bengal Agro Exports",
    contactPerson: "Arjun Kapoor",
    email: "arjun@bengalagro.in",
    phone: "+91995550108",
    country: "India",
    productCount: 205,
    status: "ACTIVE",
    notes: "Organic ingredient supplier across three categories.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-009",
    companyName: "Pearl River Electronics",
    contactPerson: "Mei Lin",
    email: "mei.lin@pearlriver.cn",
    phone: "+86105550109",
    country: "China",
    productCount: 188,
    status: "ACTIVE",
    notes: "Assembly partner with QA escalation contacts on file.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-010",
    companyName: "Kyoto Surface Works",
    contactPerson: "Hana Sato",
    email: "hana@kyotosurface.jp",
    phone: "+81355501010",
    country: "Japan",
    productCount: 35,
    status: "INACTIVE",
    notes: "Ceramic coating vendor on seasonal contract.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-011",
    companyName: "Southern Coast Produce",
    contactPerson: "Noah Wilson",
    email: "noah@southerncoastproduce.au",
    phone: "+61255501011",
    country: "Australia",
    productCount: 84,
    status: "ACTIVE",
    notes: "Cold-chain certified produce supplier.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-012",
    companyName: "Desert Falcon Logistics",
    contactPerson: "Fatima Al Mansoori",
    email: "fatima@desertfalcon.ae",
    phone: "+97145550112",
    country: "United Arab Emirates",
    productCount: 29,
    status: "PENDING",
    notes: "Regional freight and bonded warehousing partner.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-013",
    companyName: "Blue Harbor Fasteners",
    contactPerson: "Ethan Brooks",
    email: "ethan@blueharborfasteners.com",
    phone: "+12125550113",
    country: "United States",
    productCount: 112,
    status: "ACTIVE",
    notes: "Approved alternate supplier for stainless hardware.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-014",
    companyName: "Aurora Fresh Foods",
    contactPerson: "Ella Thompson",
    email: "ella@aurorafresh.ca",
    phone: "+16045550114",
    country: "Canada",
    productCount: 48,
    status: "PENDING",
    notes: "New supplier onboarding for frozen meal ingredients.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-015",
    companyName: "Azteca Tooling",
    contactPerson: "Diego Ramos",
    email: "diego@aztecatooling.mx",
    phone: "+52555550115",
    country: "Mexico",
    productCount: 67,
    status: "ACTIVE",
    notes: "Produces custom jigs for packaging automation.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-016",
    companyName: "Sao Paulo Lab Supplies",
    contactPerson: "Beatriz Costa",
    email: "beatriz@sp-labs.com.br",
    phone: "+55115550116",
    country: "Brazil",
    productCount: 18,
    status: "INACTIVE",
    notes: "Dormant account retained for emergency sourcing.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-017",
    companyName: "Albion Beverage Group",
    contactPerson: "Oliver Price",
    email: "oliver@albionbeverage.co.uk",
    phone: "+44205550117",
    country: "United Kingdom",
    productCount: 96,
    status: "ACTIVE",
    notes: "Private label beverage bottling partner.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-018",
    companyName: "Rhine Valley Glass",
    contactPerson: "Mia Weber",
    email: "mia@rhineglass.de",
    phone: "+497115550118",
    country: "Germany",
    productCount: 121,
    status: "ACTIVE",
    notes: "Glass bottle supplier with premium embossing line.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-019",
    companyName: "Marseille Marine Goods",
    contactPerson: "Leo Moreau",
    email: "leo@marseillemarine.fr",
    phone: "+3345550119",
    country: "France",
    productCount: 25,
    status: "PENDING",
    notes: "Marine equipment vendor awaiting trial shipment.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-020",
    companyName: "Punjab Engineered Fabrics",
    contactPerson: "Priya Mehta",
    email: "priya@pefabrics.in",
    phone: "+91115550120",
    country: "India",
    productCount: 133,
    status: "ACTIVE",
    notes: "Long-term supplier for technical textiles.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-021",
    companyName: "Dragon Peak Lighting",
    contactPerson: "Wei Chen",
    email: "wei@dragonpeak.cn",
    phone: "+86215550121",
    country: "China",
    productCount: 170,
    status: "ACTIVE",
    notes: "LED module supplier with expedited replacement terms.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-022",
    companyName: "Osaka Safety Systems",
    contactPerson: "Takumi Ito",
    email: "takumi@osakasafety.jp",
    phone: "+8165550122",
    country: "Japan",
    productCount: 54,
    status: "INACTIVE",
    notes: "Safety sensor supplier currently under review.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-023",
    companyName: "Tasman Cold Storage",
    contactPerson: "Zoe Carter",
    email: "zoe@tasmancold.au",
    phone: "+6135550123",
    country: "Australia",
    productCount: 39,
    status: "PENDING",
    notes: "Candidate provider for overflow warehouse space.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-024",
    companyName: "Gulf Horizon Imports",
    contactPerson: "Omar Khalid",
    email: "omar@gulfhorizon.ae",
    phone: "+971265550124",
    country: "United Arab Emirates",
    productCount: 61,
    status: "ACTIVE",
    notes: "Imports specialty materials for MENA region projects.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-025",
    companyName: "Pacific Crest Ingredients",
    contactPerson: "Grace Lee",
    email: "grace@pacificcrestingredients.com",
    phone: "+13105550125",
    country: "United States",
    productCount: 143,
    status: "ACTIVE",
    notes: "Approved with allergen-control audit completed.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-026",
    companyName: "Northern Grid Power",
    contactPerson: "Mason Clarke",
    email: "mason@northerngrid.ca",
    phone: "+15145550126",
    country: "Canada",
    productCount: 46,
    status: "INACTIVE",
    notes: "Backup generator equipment supplier.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-027",
    companyName: "Verde Agro Packaging",
    contactPerson: "Isabella Cruz",
    email: "isabella@verdeagro.mx",
    phone: "+52555550127",
    country: "Mexico",
    productCount: 72,
    status: "ACTIVE",
    notes: "Supplies compostable pouches for produce lines.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-028",
    companyName: "Amazonia Botanicals",
    contactPerson: "Rafael Santos",
    email: "rafael@amazoniabotanicals.com.br",
    phone: "+55115550128",
    country: "Brazil",
    productCount: 58,
    status: "ACTIVE",
    notes: "Botanical extracts with traceability documentation.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-029",
    companyName: "Sterling Office Supply",
    contactPerson: "Emily Harper",
    email: "emily@sterlingoffice.co.uk",
    phone: "+44205550129",
    country: "United Kingdom",
    productCount: 80,
    status: "PENDING",
    notes: "Office consumables supplier awaiting final approval.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-030",
    companyName: "Black Forest Sensors",
    contactPerson: "Felix Braun",
    email: "felix@bf-sensors.de",
    phone: "+497115550130",
    country: "Germany",
    productCount: 116,
    status: "ACTIVE",
    notes: "Core sensor partner for warehouse automation.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-031",
    companyName: "Paris Artisan Foods",
    contactPerson: "Amelie Bernard",
    email: "amelie@parisartisanfoods.fr",
    phone: "+3315550131",
    country: "France",
    productCount: 43,
    status: "ACTIVE",
    notes: "Small-batch gourmet supplier with seasonal volume swings.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
  {
    id: "sup-032",
    companyName: "Mumbai Port Logistics",
    contactPerson: "Rohan Desai",
    email: "rohan@mumbaiportlogistics.in",
    phone: "+91225550132",
    country: "India",
    productCount: 65,
    status: "ACTIVE",
    notes: "Handles import clearing for coastal shipments.",
    createdAt: baseTimestamp,
    updatedAt: baseTimestamp,
  },
];
